GET http://localhost:4000/api/



###
//* USER - REGISTER 
POST http://localhost:4000/api/register
content-type: application/json

{
  "username": "test11",
  "password": "test11",
  "passwordConfirmation": "test11",
  "email": "test@test11.com"
} 

###
//* USER - LOGIN 
POST http://localhost:4000/api/login
content-type: application/json

{
  "email": "test@test11.com",
  "password": "test11"
} 