### 

@id = 60b4e8c9eb347f37f4821d25

@moodId = 60ad0b97465525e70f28f9fb

@addedMoodId = 60b2d6fc3aa79404db286b0d

@commentId = 60b0fd8d360175615b40a62d

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGI0ZThjMGViMzQ3ZjM3ZjQ4MjFkMGEiLCJpYXQiOjE2MjI0NzI0NzAsImV4cCI6MTYyMjUxNTY3MH0.LcVb-vGbkARlvEmWRxoUWtkGC0LzYlvfNWS82Jqsnsg


###
//* MOVIE - GET ALL MOVIES
GET http://localhost:4000/api/movies

###
// * MOVIE - GET ALL MOVIES BY MOOD 
GET http://localhost:4000/api/moods/{{addedMoodId}}

###
//* MOVIE - GET ONE MOVIE
GET http://localhost:4000/api/movies/{{id}}

###
//* MOVIE - POST A MOVIE
POST http://localhost:4000/api/movies
Authorization: Bearer {{token}}
content-type: application/json

{
  "imdb": 546457, 
  "genres": 0,
  "director": ["I LOVE KEVIN COSTNER NOW"],
  "actors": ["I LOVE KEVIN COSTNER NOW"],
  "language": ["test"],
  "title": "I LOVE KEVIN COSTNER NOW",
  "year": "I LOVE KEVIN COSTNER NOW",
  "rated": "I LOVE KEVIN COSTNER NOW",
  "released": "I LOVE KEVIN COSTNER NOW",
  "runtime": "I LOVE KEVIN COSTNER NOW",
  "plot": "I LOVE KEVIN COSTNER NOW",
  "poster": "I LOVE KEVIN COSTNER NOW",
  "ratings": [{"source": "I LOVE KEVIN COSTNER NOW", "value": "I LOVE KEVIN COSTNER NOW"}, {"source": "I LOVE KEVIN COSTNER NOW", "value": "I LOVE KEVIN COSTNER NOW"}, {"source": "I LOVE KEVIN COSTNER NOW", "value": "I LOVE KEVIN COSTNER NOW"}],
  "moods": [["uplifting"]]
}

###
//* MOVIE - DELETE A MOVIE 
DELETE http://localhost:4000/api/movies/{{id}}
Authorization: Bearer {{token}}
content-type: application/json

###
//* MOVIE - UPDATE A MOVIE 
PUT http://localhost:4000/api/movies/{{id}}
Authorization: Bearer {{token}}
content-type: application/json

{
  "genres": 0,
  "director": "umm",
  "actors": "who",
  "language": "test",
  "title": "editing a movie, don't mind me",
  "year": "test",
  "rated": "test",
  "released": "test",
  "runtime": "test",
  "plot": "test",
  "poster": "test",
  "ratings": [{"source": "test", "value": "test"}, {"source": "test", "value": "test"}, {"source": "test", "value": "test"}],
  "moods": [["lol"]]
}

### 
//* MOVIE - SEARCH FOR A MOVIE
GET http://localhost:4000/api/movies/search?actors=jake

###
//* MOOD - GET ALL MOODS
GET http://localhost:4000/api/moods

###
//* USER - REGISTER A USER
POST http://localhost:4000/api/register
content-type: application/json

{
  "username": "b",
  "password": "b",
  "passwordConfirmation": "b",
  "email": "b@b.com"
} 

###
//* USER - LOGIN A USER
POST http://localhost:4000/api/login
content-type: application/json

{
  "email": "admin@email.com",
  "password": "password"
} 

###
//* MOOD - POST A MOOD
POST http://localhost:4000/api/movies/{{id}}/mood
Authorization: Bearer {{token}}
content-type: application/json

{
  "mood": "weird"
}

###
//* MOOD - DELETE A MOOD
DELETE http://localhost:4000/api/movies/{{id}}/mood/{{moodId}}
Authorization: Bearer {{token}}
content-type: application/json

###
//* COMMENT - POST A COMMENT
POST http://localhost:4000/api/movies/{{id}}/comment
Authorization: Bearer {{token}}
content-type: application/json

{
  "text": "commenting one last time?"
}

###
//* COMMENT - DELETE A COMMENT
DELETE http://localhost:4000/api/movies/{{id}}/comment/{{commentId}}
Authorization: Bearer {{token}}
content-type: application/json





